### ISSUE TITLE
Add Run Instructions

### ISSUE THREAD

**Issue by pacarvalho** [kfatehi/ichat2json#3]
Would it be possible for you to add information on how to run this application?

**Comment by unzsnu** [comment]
- Open ichat2json.xcodeproj with Xcode. 
- Build it. 
- In console you'll find the path of the executable.

Console: 
```console
Usage:  /Users/[YOURUSER]/Library/Developer/Xcode/DerivedData/ichat2json-fgxipssxrjlhvrevepwucnmapdzq/Build/Products/Debug/ichat2json path/to/ichat
```

Copy the path, and use this command in a Terminal to dump it in a file:

EX: 
```bash
cd /PATH_TO_YOUR_ICHAT_FILE
/Users/[YOURUSER]/Library/Developer/Xcode/DerivedData/ichat2json-fgxipssxrjlhvrevepwucnmapdzq/Build/Products/Debug/ichat2json file.ichat > file.json
```

**Comment by kfatehi** [comment]
@unzsnu thank you, added it to the README.md file and attributed you
